// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/product/product.proto

package product

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	SKU           string                 `protobuf:"bytes,2,opt,name=SKU,json=sku,proto3" json:"SKU,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=Quantity,json=quantity,proto3" json:"Quantity,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=Price,json=price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_api_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Product) GetSKU() string {
	if x != nil {
		return x.SKU
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Product) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductsRequest) Reset() {
	*x = CreateProductsRequest{}
	mi := &file_api_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductsRequest) ProtoMessage() {}

func (x *CreateProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductsRequest.ProtoReflect.Descriptor instead.
func (*CreateProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductsRequest) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type CreateProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductsReply) Reset() {
	*x = CreateProductsReply{}
	mi := &file_api_product_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductsReply) ProtoMessage() {}

func (x *CreateProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductsReply.ProtoReflect.Descriptor instead.
func (*CreateProductsReply) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{2}
}

type UpdateProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsRequest) Reset() {
	*x = UpdateProductsRequest{}
	mi := &file_api_product_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsRequest) ProtoMessage() {}

func (x *UpdateProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{3}
}

type UpdateProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsReply) Reset() {
	*x = UpdateProductsReply{}
	mi := &file_api_product_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsReply) ProtoMessage() {}

func (x *UpdateProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsReply.ProtoReflect.Descriptor instead.
func (*UpdateProductsReply) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{4}
}

type DeleteProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductsRequest) Reset() {
	*x = DeleteProductsRequest{}
	mi := &file_api_product_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductsRequest) ProtoMessage() {}

func (x *DeleteProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductsRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{5}
}

type DeleteProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductsReply) Reset() {
	*x = DeleteProductsReply{}
	mi := &file_api_product_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductsReply) ProtoMessage() {}

func (x *DeleteProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductsReply.ProtoReflect.Descriptor instead.
func (*DeleteProductsReply) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{6}
}

type GetProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsRequest) Reset() {
	*x = GetProductsRequest{}
	mi := &file_api_product_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsRequest) ProtoMessage() {}

func (x *GetProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{7}
}

type GetProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsReply) Reset() {
	*x = GetProductsReply{}
	mi := &file_api_product_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsReply) ProtoMessage() {}

func (x *GetProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsReply.ProtoReflect.Descriptor instead.
func (*GetProductsReply) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{8}
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_api_product_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{9}
}

type ListProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsReply) Reset() {
	*x = ListProductsReply{}
	mi := &file_api_product_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsReply) ProtoMessage() {}

func (x *ListProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsReply.ProtoReflect.Descriptor instead.
func (*ListProductsReply) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{10}
}

var File_api_product_product_proto protoreflect.FileDescriptor

const file_api_product_product_proto_rawDesc = "" +
	"\n" +
	"\x19api/product/product.proto\x12\vapi.product\x1a\x1cgoogle/api/annotations.proto\"q\n" +
	"\aProduct\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03SKU\x18\x02 \x01(\tR\x03sku\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bQuantity\x18\x04 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05Price\x18\x05 \x01(\x03R\x05price\"I\n" +
	"\x15CreateProductsRequest\x120\n" +
	"\bproducts\x18\x01 \x03(\v2\x14.api.product.ProductR\bproducts\"\x15\n" +
	"\x13CreateProductsReply\"\x17\n" +
	"\x15UpdateProductsRequest\"\x15\n" +
	"\x13UpdateProductsReply\"\x17\n" +
	"\x15DeleteProductsRequest\"\x15\n" +
	"\x13DeleteProductsReply\"\x14\n" +
	"\x12GetProductsRequest\"\x12\n" +
	"\x10GetProductsReply\"\x15\n" +
	"\x13ListProductsRequest\"\x13\n" +
	"\x11ListProductsReply2\xc9\x03\n" +
	"\bProducts\x12l\n" +
	"\x0eCreateProducts\x12\".api.product.CreateProductsRequest\x1a .api.product.CreateProductsReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/products\x12V\n" +
	"\x0eUpdateProducts\x12\".api.product.UpdateProductsRequest\x1a .api.product.UpdateProductsReply\x12V\n" +
	"\x0eDeleteProducts\x12\".api.product.DeleteProductsRequest\x1a .api.product.DeleteProductsReply\x12M\n" +
	"\vGetProducts\x12\x1f.api.product.GetProductsRequest\x1a\x1d.api.product.GetProductsReply\x12P\n" +
	"\fListProducts\x12 .api.product.ListProductsRequest\x1a\x1e.api.product.ListProductsReplyB1\n" +
	"\fapi.productsP\x01Z\x1fgo-products/api/product;productb\x06proto3"

var (
	file_api_product_product_proto_rawDescOnce sync.Once
	file_api_product_product_proto_rawDescData []byte
)

func file_api_product_product_proto_rawDescGZIP() []byte {
	file_api_product_product_proto_rawDescOnce.Do(func() {
		file_api_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_product_product_proto_rawDesc), len(file_api_product_product_proto_rawDesc)))
	})
	return file_api_product_product_proto_rawDescData
}

var file_api_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_product_product_proto_goTypes = []any{
	(*Product)(nil),               // 0: api.product.Product
	(*CreateProductsRequest)(nil), // 1: api.product.CreateProductsRequest
	(*CreateProductsReply)(nil),   // 2: api.product.CreateProductsReply
	(*UpdateProductsRequest)(nil), // 3: api.product.UpdateProductsRequest
	(*UpdateProductsReply)(nil),   // 4: api.product.UpdateProductsReply
	(*DeleteProductsRequest)(nil), // 5: api.product.DeleteProductsRequest
	(*DeleteProductsReply)(nil),   // 6: api.product.DeleteProductsReply
	(*GetProductsRequest)(nil),    // 7: api.product.GetProductsRequest
	(*GetProductsReply)(nil),      // 8: api.product.GetProductsReply
	(*ListProductsRequest)(nil),   // 9: api.product.ListProductsRequest
	(*ListProductsReply)(nil),     // 10: api.product.ListProductsReply
}
var file_api_product_product_proto_depIdxs = []int32{
	0,  // 0: api.product.CreateProductsRequest.products:type_name -> api.product.Product
	1,  // 1: api.product.Products.CreateProducts:input_type -> api.product.CreateProductsRequest
	3,  // 2: api.product.Products.UpdateProducts:input_type -> api.product.UpdateProductsRequest
	5,  // 3: api.product.Products.DeleteProducts:input_type -> api.product.DeleteProductsRequest
	7,  // 4: api.product.Products.GetProducts:input_type -> api.product.GetProductsRequest
	9,  // 5: api.product.Products.ListProducts:input_type -> api.product.ListProductsRequest
	2,  // 6: api.product.Products.CreateProducts:output_type -> api.product.CreateProductsReply
	4,  // 7: api.product.Products.UpdateProducts:output_type -> api.product.UpdateProductsReply
	6,  // 8: api.product.Products.DeleteProducts:output_type -> api.product.DeleteProductsReply
	8,  // 9: api.product.Products.GetProducts:output_type -> api.product.GetProductsReply
	10, // 10: api.product.Products.ListProducts:output_type -> api.product.ListProductsReply
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_product_product_proto_init() }
func file_api_product_product_proto_init() {
	if File_api_product_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_product_product_proto_rawDesc), len(file_api_product_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_product_product_proto_goTypes,
		DependencyIndexes: file_api_product_product_proto_depIdxs,
		MessageInfos:      file_api_product_product_proto_msgTypes,
	}.Build()
	File_api_product_product_proto = out.File
	file_api_product_product_proto_goTypes = nil
	file_api_product_product_proto_depIdxs = nil
}
