// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v6.30.2
// source: api/product/product.proto

package product

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationProductsCreateProducts = "/api.product.Products/CreateProducts"

type ProductsHTTPServer interface {
	CreateProducts(context.Context, *CreateProductsRequest) (*CreateProductsReply, error)
}

func RegisterProductsHTTPServer(s *http.Server, srv ProductsHTTPServer) {
	r := s.Route("/")
	r.POST("/products", _Products_CreateProducts0_HTTP_Handler(srv))
}

func _Products_CreateProducts0_HTTP_Handler(srv ProductsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateProductsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationProductsCreateProducts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateProducts(ctx, req.(*CreateProductsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateProductsReply)
		return ctx.Result(200, reply)
	}
}

type ProductsHTTPClient interface {
	CreateProducts(ctx context.Context, req *CreateProductsRequest, opts ...http.CallOption) (rsp *CreateProductsReply, err error)
}

type ProductsHTTPClientImpl struct {
	cc *http.Client
}

func NewProductsHTTPClient(client *http.Client) ProductsHTTPClient {
	return &ProductsHTTPClientImpl{client}
}

func (c *ProductsHTTPClientImpl) CreateProducts(ctx context.Context, in *CreateProductsRequest, opts ...http.CallOption) (*CreateProductsReply, error) {
	var out CreateProductsReply
	pattern := "/products"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationProductsCreateProducts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
