-- Create "products" table
CREATE TABLE "products" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "delete_time" timestamptz NULL,
  "sku" uuid NULL,
  "name" character varying NOT NULL,
  "quantity" bigint NOT NULL,
  "price" bigint NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "products_sku_key" to table: "products"
CREATE UNIQUE INDEX "products_sku_key" ON "products" ("sku");
