// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/product/product.proto

package product

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_api_product_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_api_product_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{1}
}

func (x *CommonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommonResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	SKU           string                 `protobuf:"bytes,2,opt,name=SKU,json=sku,proto3" json:"SKU,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,json=name,proto3" json:"Name,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=Quantity,json=quantity,proto3" json:"Quantity,omitempty"`
	Price         int64                  `protobuf:"varint,5,opt,name=Price,json=price,proto3" json:"Price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_api_product_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Product) GetSKU() string {
	if x != nil {
		return x.SKU
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Product) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductsRequest) Reset() {
	*x = CreateProductsRequest{}
	mi := &file_api_product_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductsRequest) ProtoMessage() {}

func (x *CreateProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductsRequest.ProtoReflect.Descriptor instead.
func (*CreateProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProductsRequest) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type CreateProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *CommonResponse        `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductsReply) Reset() {
	*x = CreateProductsReply{}
	mi := &file_api_product_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductsReply) ProtoMessage() {}

func (x *CreateProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductsReply.ProtoReflect.Descriptor instead.
func (*CreateProductsReply) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProductsReply) GetMeta() *CommonResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

type UpdateProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsRequest) Reset() {
	*x = UpdateProductsRequest{}
	mi := &file_api_product_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsRequest) ProtoMessage() {}

func (x *UpdateProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProductsRequest) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type UpdateProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *CommonResponse        `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductsReply) Reset() {
	*x = UpdateProductsReply{}
	mi := &file_api_product_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductsReply) ProtoMessage() {}

func (x *UpdateProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductsReply.ProtoReflect.Descriptor instead.
func (*UpdateProductsReply) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProductsReply) GetMeta() *CommonResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

type DeleteProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductsRequest) Reset() {
	*x = DeleteProductsRequest{}
	mi := &file_api_product_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductsRequest) ProtoMessage() {}

func (x *DeleteProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductsRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProductsRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

type DeleteProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *CommonResponse        `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductsReply) Reset() {
	*x = DeleteProductsReply{}
	mi := &file_api_product_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductsReply) ProtoMessage() {}

func (x *DeleteProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductsReply.ProtoReflect.Descriptor instead.
func (*DeleteProductsReply) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteProductsReply) GetMeta() *CommonResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_api_product_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{9}
}

func (x *GetProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

type GetProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Meta          *CommonResponse        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReply) Reset() {
	*x = GetProductReply{}
	mi := &file_api_product_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReply) ProtoMessage() {}

func (x *GetProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReply.ProtoReflect.Descriptor instead.
func (*GetProductReply) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{10}
}

func (x *GetProductReply) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *GetProductReply) GetMeta() *CommonResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=pageSize,json=page_size,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_api_product_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{11}
}

func (x *ListProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Meta          *CommonResponse        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsReply) Reset() {
	*x = ListProductsReply{}
	mi := &file_api_product_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsReply) ProtoMessage() {}

func (x *ListProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_product_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsReply.ProtoReflect.Descriptor instead.
func (*ListProductsReply) Descriptor() ([]byte, []int) {
	return file_api_product_product_proto_rawDescGZIP(), []int{12}
}

func (x *ListProductsReply) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsReply) GetMeta() *CommonResponse {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_api_product_product_proto protoreflect.FileDescriptor

const file_api_product_product_proto_rawDesc = "" +
	"\n" +
	"\x19api/product/product.proto\x12\vapi.product\x1a\x1cgoogle/api/annotations.proto\"3\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"n\n" +
	"\x0eCommonResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x05error\x18\x03 \x01(\v2\x12.api.product.ErrorR\x05error\"q\n" +
	"\aProduct\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03SKU\x18\x02 \x01(\tR\x03sku\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bQuantity\x18\x04 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05Price\x18\x05 \x01(\x03R\x05price\"I\n" +
	"\x15CreateProductsRequest\x120\n" +
	"\bproducts\x18\x01 \x03(\v2\x14.api.product.ProductR\bproducts\"F\n" +
	"\x13CreateProductsReply\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.api.product.CommonResponseR\x04meta\"G\n" +
	"\x15UpdateProductsRequest\x12.\n" +
	"\aproduct\x18\x01 \x01(\v2\x14.api.product.ProductR\aproduct\"F\n" +
	"\x13UpdateProductsReply\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.api.product.CommonResponseR\x04meta\")\n" +
	"\x15DeleteProductsRequest\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\"F\n" +
	"\x13DeleteProductsReply\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.api.product.CommonResponseR\x04meta\"5\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\"r\n" +
	"\x0fGetProductReply\x12.\n" +
	"\aproduct\x18\x01 \x01(\v2\x14.api.product.ProductR\aproduct\x12/\n" +
	"\x04meta\x18\x02 \x01(\v2\x1b.api.product.CommonResponseR\x04meta\"F\n" +
	"\x13ListProductsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\bpageSize\x18\x02 \x01(\x05R\tpage_size\"v\n" +
	"\x11ListProductsReply\x120\n" +
	"\bproducts\x18\x01 \x03(\v2\x14.api.product.ProductR\bproducts\x12/\n" +
	"\x04meta\x18\x02 \x01(\v2\x1b.api.product.CommonResponseR\x04meta2\xb7\x04\n" +
	"\bProducts\x12l\n" +
	"\x0eCreateProducts\x12\".api.product.CreateProductsRequest\x1a .api.product.CreateProductsReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/products\x12l\n" +
	"\x0eUpdateProducts\x12\".api.product.UpdateProductsRequest\x1a .api.product.UpdateProductsReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\x1a\t/products\x12o\n" +
	"\x0eDeleteProducts\x12\".api.product.DeleteProductsRequest\x1a .api.product.DeleteProductsReply\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/products/{sku}\x12c\n" +
	"\fListProducts\x12 .api.product.ListProductsRequest\x1a\x1e.api.product.ListProductsReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/products\x12y\n" +
	"\n" +
	"GetProduct\x12\x1e.api.product.GetProductRequest\x1a\x1c.api.product.GetProductReply\"-\x82\xd3\xe4\x93\x02'Z\x15\x12\x13/products/sku/{sku}\x12\x0e/products/{id}B1\n" +
	"\fapi.productsP\x01Z\x1fgo-products/api/product;productb\x06proto3"

var (
	file_api_product_product_proto_rawDescOnce sync.Once
	file_api_product_product_proto_rawDescData []byte
)

func file_api_product_product_proto_rawDescGZIP() []byte {
	file_api_product_product_proto_rawDescOnce.Do(func() {
		file_api_product_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_product_product_proto_rawDesc), len(file_api_product_product_proto_rawDesc)))
	})
	return file_api_product_product_proto_rawDescData
}

var file_api_product_product_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_product_product_proto_goTypes = []any{
	(*Error)(nil),                 // 0: api.product.Error
	(*CommonResponse)(nil),        // 1: api.product.CommonResponse
	(*Product)(nil),               // 2: api.product.Product
	(*CreateProductsRequest)(nil), // 3: api.product.CreateProductsRequest
	(*CreateProductsReply)(nil),   // 4: api.product.CreateProductsReply
	(*UpdateProductsRequest)(nil), // 5: api.product.UpdateProductsRequest
	(*UpdateProductsReply)(nil),   // 6: api.product.UpdateProductsReply
	(*DeleteProductsRequest)(nil), // 7: api.product.DeleteProductsRequest
	(*DeleteProductsReply)(nil),   // 8: api.product.DeleteProductsReply
	(*GetProductRequest)(nil),     // 9: api.product.GetProductRequest
	(*GetProductReply)(nil),       // 10: api.product.GetProductReply
	(*ListProductsRequest)(nil),   // 11: api.product.ListProductsRequest
	(*ListProductsReply)(nil),     // 12: api.product.ListProductsReply
}
var file_api_product_product_proto_depIdxs = []int32{
	0,  // 0: api.product.CommonResponse.error:type_name -> api.product.Error
	2,  // 1: api.product.CreateProductsRequest.products:type_name -> api.product.Product
	1,  // 2: api.product.CreateProductsReply.meta:type_name -> api.product.CommonResponse
	2,  // 3: api.product.UpdateProductsRequest.product:type_name -> api.product.Product
	1,  // 4: api.product.UpdateProductsReply.meta:type_name -> api.product.CommonResponse
	1,  // 5: api.product.DeleteProductsReply.meta:type_name -> api.product.CommonResponse
	2,  // 6: api.product.GetProductReply.product:type_name -> api.product.Product
	1,  // 7: api.product.GetProductReply.meta:type_name -> api.product.CommonResponse
	2,  // 8: api.product.ListProductsReply.products:type_name -> api.product.Product
	1,  // 9: api.product.ListProductsReply.meta:type_name -> api.product.CommonResponse
	3,  // 10: api.product.Products.CreateProducts:input_type -> api.product.CreateProductsRequest
	5,  // 11: api.product.Products.UpdateProducts:input_type -> api.product.UpdateProductsRequest
	7,  // 12: api.product.Products.DeleteProducts:input_type -> api.product.DeleteProductsRequest
	11, // 13: api.product.Products.ListProducts:input_type -> api.product.ListProductsRequest
	9,  // 14: api.product.Products.GetProduct:input_type -> api.product.GetProductRequest
	4,  // 15: api.product.Products.CreateProducts:output_type -> api.product.CreateProductsReply
	6,  // 16: api.product.Products.UpdateProducts:output_type -> api.product.UpdateProductsReply
	8,  // 17: api.product.Products.DeleteProducts:output_type -> api.product.DeleteProductsReply
	12, // 18: api.product.Products.ListProducts:output_type -> api.product.ListProductsReply
	10, // 19: api.product.Products.GetProduct:output_type -> api.product.GetProductReply
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_product_product_proto_init() }
func file_api_product_product_proto_init() {
	if File_api_product_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_product_product_proto_rawDesc), len(file_api_product_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_product_product_proto_goTypes,
		DependencyIndexes: file_api_product_product_proto_depIdxs,
		MessageInfos:      file_api_product_product_proto_msgTypes,
	}.Build()
	File_api_product_product_proto = out.File
	file_api_product_product_proto_goTypes = nil
	file_api_product_product_proto_depIdxs = nil
}
