// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package product

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID        int64
	Sku       string
	Name      string
	Quantity  int64
	Price     int64
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}
