### Create PRoducts
POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json

{
  "products": [
    { "sku": "SKU001", "name": "Gula", "price": 12500, "quantity": 173 },
    { "sku": "SKU002", "name": "Kopi", "price": 18500, "quantity": 95 },
    { "sku": "SKU003", "name": "Minyak Goreng", "price": 28000, "quantity": 120 },
    { "sku": "SKU004", "name": "Tepung Terigu", "price": 10500, "quantity": 88 },
    { "sku": "SKU005", "name": "Beras", "price": 54000, "quantity": 210 },
    { "sku": "SKU006", "name": "Kecap", "price": 8500, "quantity": 150 },
    { "sku": "SKU007", "name": "Sabun Cuci", "price": 6000, "quantity": 60 },
    { "sku": "SKU008", "name": "Mie Instan", "price": 3000, "quantity": 450 },
    { "sku": "SKU009", "name": "Susu Kental", "price": 11000, "quantity": 78 },
    { "sku": "SKU010", "name": "Garam", "price": 4000, "quantity": 200 }
  ]
}


### Get Products by ID
GET http://localhost:8000/products/10 HTTP/1.1
Content-Type: application/json

### Get Products by SKU
GET http://localhost:8000/products/sku/SKU010 HTTP/1.1
Content-Type: application/json