-- Buat tabel products
CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sku         VARCHAR(16) NOT NULL,
    name        VARCHAR(64) NOT NULL,
    quantity    BIGINT NOT NULL,
    price       BIGINT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT (timezone('utc', now())),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT (timezone('utc', now())),
    deleted_at  TIMESTAMP,

    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT products_sku_key UNIQUE (sku)
);
